### PR TITLE
ENH: Split and persist CI jobs & artifacts

### LINKED ISSUE #134: ENH: Speed up build+test
Why do we build installers for two versions of each OS (plus M1)? It seems like we should build just on the oldest one for each OS (plus M1), then test on the oldest and the newest version of each OS (plus M1). In other words, it seems like we should have two stages: the first "build" stage on 4 OSes (old ubuntu/mac/win + M1), and a second "test" stage on 7 OSes (old/new x ubuntu/mac/win, plus M1).

### PR DESCRIPTION
**Pull request by larsoner**
Closes #134

### CODE REVIEW

**Comment by larsoner** [comment]
Ouch, upload takes ~7 minutes. Then all tests are bottlenecked until all 4 of the build jobs finish. I'm becoming skeptical that this will actually help us very much. @hoechenberger WDYT?

**Comment by larsoner** [comment]
(download only takes ~1 minute at least)

**Comment by hoechenberger** [comment]
@larsoner What's your gut feeling on the added-enhancements-to-added-complexity ratio here?

**Comment by larsoner** [comment]
> @larsoner What's your gut feeling on the added-enhancements-to-added-complexity ratio here?

I don't think the complexity is too bad. If anything I think it's nice because it totally isolates the build process from the install process. They happen effectively on different machines now, which is nice.

What I was worried about was additional overhead. I thought this would speed things up but the upload time is so long that I think it's roughly the same as it was before in terms of push-to-green. In terms of overall time, it looks like this PR used ~123min of total CI time on my last push. The last build on `main` used 135 min. So they're pretty comparable in terms of overall utilization.

So overall I'm +1 for merge now

**Comment by hoechenberger** [comment]
Thanks @larsoner!!!!

**Pull request merged**
