### PR TITLE
Include MNE-ICALabel for macOS and Linux

### PR DESCRIPTION
**Pull request by hoechenberger**

### CODE REVIEW

**Comment by hoechenberger** [comment]
All green, but on Windows the `mne_icalabel` import produces

```python
2022-05-10T21:54:46.8675156Z Traceback (most recent call last):
2022-05-10T21:54:46.8679942Z   File "D:\a\mne-installers\mne-installers\tests\test_imports.py", line 12, in <module>
2022-05-10T21:54:46.8681235Z     import mne_icalabel
2022-05-10T21:54:46.8681827Z   File "C:\Users\runneradmin\mne-python\1.0.2_1\lib\site-packages\mne_icalabel\__init__.py", line 10, in <module>
2022-05-10T21:54:46.8682427Z     from .label_components import label_components  # noqa: F401
2022-05-10T21:54:46.8683047Z   File "C:\Users\runneradmin\mne-python\1.0.2_1\lib\site-packages\mne_icalabel\label_components.py", line 10, in <module>
2022-05-10T21:54:46.8683646Z     from .iclabel import iclabel_label_components
2022-05-10T21:54:46.8684249Z   File "C:\Users\runneradmin\mne-python\1.0.2_1\lib\site-packages\mne_icalabel\iclabel\__init__.py", line 7, in <module>
2022-05-10T21:54:46.8684925Z     from .label_components import iclabel_label_components  # noqa: F401
2022-05-10T21:54:46.8685881Z   File "C:\Users\runneradmin\mne-python\1.0.2_1\lib\site-packages\mne_icalabel\iclabel\label_components.py", line 8, in <module>
2022-05-10T21:54:46.8686528Z     from .network import run_iclabel
2022-05-10T21:54:46.8687091Z   File "C:\Users\runneradmin\mne-python\1.0.2_1\lib\site-packages\mne_icalabel\iclabel\network.py", line 7, in <module>
2022-05-10T21:54:46.8687704Z     import torch
2022-05-10T21:54:46.8688229Z   File "C:\Users\runneradmin\mne-python\1.0.2_1\lib\site-packages\torch\__init__.py", line 126, in <module>
2022-05-10T21:54:46.8688722Z     raise err
2022-05-10T21:54:46.8689546Z OSError: [WinError 182] The operating system cannot run %1. Error loading "C:\Users\runneradmin\mne-python\1.0.2_1\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
```

**Comment by hoechenberger** [comment]
@larsoner Any idea why CI isn't aborting if Python throws an exception during one of our import tests?

**Comment by hoechenberger** [comment]
For now I'm **dropping** Windows support for MNE-ICALabel as there are currently no Windows builds of PyTorch available from `conda-forge`; and when trying to use the official `pytorch` channel, I run into an DLL problem, which apparently can be resolved when using certain packages (`intel-openmp` and potentially others) from the `defaults` channel; however, Anaconda Inc.'s [terms of service](https://www.anaconda.com/terms-of-service) could put some of our users at risk if they want to create a commercial product, if I'm not mistaken… @larsoner I suppose your English-foo for lawyer speak is much better than mine, could you take a look at the TOS and tell me what you think?

**Comment by larsoner** [comment]
IANAL so I don't really know, but it doesn't seem worth the risk

**Pull request merged**
