### PR TITLE
Add mne-lsl

### PR DESCRIPTION
**Pull request by mscheltienne**
Adding `mne-lsl` to the installers.
Should we keep `mne-realtime`, people mentioned it was not working with the latest version of MNE anyway?

### CODE REVIEW

**Comment by hoechenberger** [comment]
What's the difference between realtime and LSL? Can MNE-LSL replace MNE-realtime for LSL users?

**Comment by drammock** [comment]
> What's the difference between realtime and LSL? 

MNE-LSL is a rewrite of much of MNE-Realtime functionality, but built on top of LSL from the start (MNE-Realtime was built around FieldTripBuffer, with limited LSL support added later). 

> Can MNE-LSL replace MNE-realtime for LSL users?

yes, that is the intent.

**Comment by mscheltienne** [comment]
It's still a WIP on which I work on when I have the time, but it is functional and already simplifies a lot the interaction with an LSL stream.

**Comment by hoechenberger** [comment]
Thanks @drammock and @mscheltienne!

I just saw that you were planning to deprecate the MNE-Realtime package anyway, so from my end I have no objections to removing it and adding MNE-LSL to the installer.

**Review by hoechenberger — CHANGES_REQUESTED** [review]
Please add an import test to `test_imports.py` and bump the versions of all other outdated packages in a separate commit. I think then it'll be ready to merge.

**Comment by larsoner** [comment]
`mne-realtime` should in principle continue to work. Let's keep it for a release or two

**Review by hoechenberger — APPROVED** [review]

**Pull request merged**
