### PR TITLE
Fix OpenBLAS issue on M1 and bump MNE to latest main snapshot

### PR DESCRIPTION
**Pull request by hoechenberger**
Builds will fail until https://github.com/conda-forge/mne-feedstock/pull/103 hits the CDN

cc @larsoner

### CODE REVIEW

**Comment by larsoner** [comment]
Is it possible the `dev` branch was never migrated to `arm64`? I don't see it in https://anaconda.org/conda-forge/mne/files

**Comment by larsoner** [comment]
https://github.com/conda-forge/mne-feedstock/pull/104 should fix it. Will wait until it merges then bump to `20220728`, which should fail. But hopefully by the time you wake up @hoechenberger you can restart the CIs and see things green!

**Comment by hoechenberger** [comment]
Thanks @larsoner, let's see how this goes now!

**Comment by hoechenberger** [comment]
@larsoner Same problem with MSYS2 and bash as in #144

**Comment by hoechenberger** [comment]
@larsoner I added a new tag and CI is currently processing.

**Comment by hoechenberger** [comment]
@larsoner Something is wrong with Windows installer artifact retrieval for testing. I won't be able to look into this until tomorrow or so

**Comment by hoechenberger** [comment]
Seems to be a naming issue in our workflow file 

Working job:
image

Failing job:
image

**Comment by hoechenberger** [comment]
@larsoner 

With the latest build (`-pre4`), the following works flawlessly on my M1 machine!

```python
import numpy as np
np.linalg.svd(np.ones((50, 50)))
```

**Comment by larsoner** [comment]
Hooray!

**Pull request merged**
