### PR TITLE
Use MNE-Python 1.0.0 stable

### PR DESCRIPTION
**Pull request by hoechenberger**
cc @larsoner

Will fail until the new packages are on the CDN

### CODE REVIEW

**Comment by larsoner** [comment]
FYI I've put this in step 17 in https://github.com/mne-tools/mne-installers/pull/105

**Comment by larsoner** [comment]
... I mean https://github.com/mne-tools/mne-python/wiki/How-to-make-a-release

**Comment by larsoner** [comment]
@hoechenberger I say we merge this once green so that we have some working installers, then update the URLs on the homepage to use them. That takes away any time pressure from release.

Then we merge https://github.com/conda-forge/mne-feedstock/pull/88, rebuild in another PR here, and iterate until they work on all platforms. Once they do, we can update the installer pages again. WDYT?

**Comment by hoechenberger** [comment]
Yes +100 for me

**Comment by hoechenberger** [comment]
I'm off for the rest of the day, do what you think is best. We'll send out the announcement tomorow, right? @agramfort

**Comment by larsoner** [comment]
I tested the draft pre10 on all three platforms and things appeared to work, so I cut a new `v1.0.0` non-draft, non-prerelease version (+tag). Once the assets show up, I'll update the installation instructions with `[circle deploy]` for both. Then I think things will be all set for release announcements (I edited the google doc @agramfort) tomorrow

**Comment by hoechenberger** [comment]
Amazing. Thanks so much @larsoner 

I'm also feeling comfortable with tuning and improving the installer whenever an idea or an issue pops up. In the worst case, users can always go back to using our conda install instructions if the installer doesn't work in their system until we provide a fix.

**Pull request merged**
