### PR TITLE
Bump pycrostates version

### PR DESCRIPTION
**Pull request by mscheltienne**
Version 0.3.0 released with improvements + compatibility for recent version of matplotlib and python.
Should be available today on conda-forge: https://github.com/conda-forge/pycrostates-feedstock/pull/9

### CODE REVIEW

**Comment by hoechenberger** [comment]
Is it in conda-forge already?

**Comment by mscheltienne** [comment]
Just now: https://anaconda.org/conda-forge/pycrostates

**Review by hoechenberger — APPROVED** [review]

**Comment by larsoner** [comment]
GitHub is having a bad day. I'll probably just roll the 1.4 release into this PR to save some CI cycles.

**Comment by hoechenberger** [comment]
@larsoner Time to cut a GH release?

**Comment by larsoner** [comment]
Yes good idea! https://github.com/mne-tools/mne-installers/releases/tag/v1.4.0

**Pull request merged**
