### PR TITLE
Try to fix artifact storage & retrieval for release

### PR DESCRIPTION
**Pull request by hoechenberger**

### CODE REVIEW

**Comment by hoechenberger** [comment]
> No idea why this changed, must be a conda infrastructure thing (?)

I suppose it's because I switched to using MSYS2 on Windows.

In any case, keeping this for now for the artifact **identifier** used for up-/downloading on our CI system, while dropping the suffix from our produced artifact **filenames**

**Comment by larsoner** [comment]
> keeping this for now for the artifact identifier used for up-/downloading on our CI system

Can we change this, too? It would be nice not to have to remember or see this weird extra name anywhere other than our standard name-mangling location `tools/extract_version.sh`

**Comment by hoechenberger** [comment]
> > keeping this for now for the artifact identifier used for up-/downloading on our CI system
> 
> Can we change this, too? It would be nice not to have to remember or see this weird extra name anywhere other than our standard name-mangling location `tools/extract_version.sh`

No idea, I have to admit I can barely figure out anymore what's going on and where; things have gotten too complex for to handle for my limited shell skills :(

**Comment by hoechenberger** [comment]
@larsoner One difficulty is that the architecture during **downloading** artifacts for the release is different from the arch during **uploading**, as we do the release on Ubuntu for all artifacts.

**Comment by larsoner** [comment]
:+1: 

Screenshot from 2022-07-28 14-29-01

**Comment by hoechenberger** [comment]
@larsoner Artifacts for testing should appear at https://github.com/mne-tools/mne-installers/releases/tag/untagged-206c90cf42605d7206d3 any minute now.

**Pull request merged**
