### PR TITLE
ENH: Use better launchers

### PR DESCRIPTION
**Pull request by larsoner**
Will hopefully pick up https://github.com/conda-forge/mne-feedstock/pull/88 once CDNs update. Then we could test on all platforms, cut a new v1.0.0_1 release, and update MNE-Python docs again.

### CODE REVIEW

**Comment by larsoner** [comment]
Can't resist at least getting the ball rolling and testing on macOS :)

**Comment by larsoner** [comment]
FYI @hoechenberger I am going to try https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ using VirtualBox on my macOS laptop to see if I can evaluate our Windows installers... wish me luck :)

**Comment by hoechenberger** [comment]
amazing!

**Comment by larsoner** [comment]
@hoechenberger updated and tested on Windows (using the dev image on VirtualBox on my macOS machine it was easy!), all looks good there. Feel free to publish https://github.com/mne-tools/mne-installers/releases/tag/untagged-1ee90cb5d53dd05aac3d !

**Pull request merged**
