### PR TITLE
ENH: Use 3.11

### PR DESCRIPTION
**Pull request by larsoner**
Now that https://github.com/conda-forge/sleepecg-feedstock/pull/22 is in let's see if it works!

Also sets us up for 1.5 because we'll probably release that soon

### CODE REVIEW

**Comment by larsoner** [comment]
Worked for everything but Linux! On Monday I'll look to see where the conflict is coming from

**Comment by hoechenberger** [comment]
This means we can start shipping TensorFlow now too

**Comment by larsoner** [comment]
Held up by https://github.com/conda-forge/vtk-feedstock/pull/302 (and maybe https://github.com/conda-forge/mayavi-feedstock/pull/75)

**Comment by larsoner** [comment]
Now held up by https://github.com/conda-forge/xorg-libxt-feedstock/issues/14

**Comment by larsoner** [comment]
All green, in it goes!!!

**Review by hoechenberger — COMMENTED** [review]
very nice

**Pull request merged**
