### PR TITLE
bump versions for MNE-Python 1.3 release

### PR DESCRIPTION
**Pull request by drammock**
@hoechenberger @larsoner please double-check my version bumps, not sure whether I caught everything, and I haven't been keeping on top of the ongoing conversations here very well.

### CODE REVIEW

**Comment by larsoner** [comment]
How did this pass before we merged the conda forge 1.3 bump? Or am I misreading the order here?

**Comment by larsoner** [comment]
Ahh there is one more file to change...

**Comment by larsoner** [comment]
Okay I changed the current_version.txt. It should fail since 1.3 hasn't hit CDNs yet but when we restart CIs in a couple of hours it should succeed, then we can merge and publish a new release here

**Comment by larsoner** [comment]
Needs https://github.com/conda-forge/mne-ari-feedstock/pull/5

**Comment by larsoner** [comment]
Whoops, need to fix mne-nirs

**Comment by larsoner** [comment]
Finally worked:

https://github.com/mne-tools/mne-installers/releases/tag/v1.3.0

**Comment by hoechenberger** [comment]
Great!

**Pull request merged**
